// Badge / Achievement system for 우리산
// 100 badges grouped into 10 categories.

enum BadgeType {
  // ── 🏃 횟수 (Count) ─────────────────────────────
  firstHike,
  hikes5,
  hikes10,
  hikes25,
  hikes50,
  hikes100,
  hikes200,
  hikes365,
  hikes500,
  hikes1000,

  // ── 📏 거리 (Distance) ──────────────────────────
  distance10km,
  distance50km,
  distance100km,
  distance200km,
  distance500km,
  distance1000km,
  distance2000km,
  distance3000km,
  distance5000km,
  distance10000km,

  // ── ⛰️ 고도 (Elevation) ─────────────────────────
  elevation500m,
  elevation1000m,
  elevation1500m,
  elevation5000m,
  elevation10000m,
  elevation50000m,
  singleHike500m,
  singleHike1000m,
  peak1000m,
  peak1500m,

  // ── 🗺️ 지역 (Region) ───────────────────────────
  regions3,
  regions5,
  regions8,
  regions10,
  regions15,
  allRegions,
  islandMountain,
  capitalArea5,

  // ── 🎖️ 도장 (Stamps) ───────────────────────────
  stamps5,
  stamps10,
  stamps25,
  stamps50,
  stamps75,
  stamps100,
  stamps150,
  stamps200,
  stamps250,
  stamps300,

  // ── 🤝 함께 (Together) ──────────────────────────
  together1,
  together5,
  together10,
  together25,
  together50,
  together100,
  togetherStreak3,
  togetherStreak7,

  // ── ⏰ 시간 (Time) ──────────────────────────────
  earlyBird,
  dawnHiker,
  nightHiker,
  longHike4h,
  longHike6h,
  longHike8h,
  longHike10h,
  quickHike1h,
  sunriseHike,
  sunsetHike,

  // ── 📅 꾸준함 (Consistency) ─────────────────────
  streakWeek,
  streak2weeks,
  streak30days,
  monthlyChallenger,
  monthly8,
  yearlyHiker,
  yearly50,
  yearly100,
  allSeasons,
  everyMonth,

  // ── 💪 도전 (Challenge) ─────────────────────────
  weekendWarrior,
  weekdayHiker,
  rainHiker,
  winterHiker,
  summerHiker,
  speedDemon,
  distanceDay20km,
  multiPeak3,
  backToBack,
  centurion,

  // ── 🌟 특수 (Special) ───────────────────────────
  newYear,
  springBloom,
  summerSolstice,
  autumnLeaves,
  winterSolstice,
  fullMoon,
  birthday,
  anniversary100,
  milestone50stamps,
  explorer20regions,
  grandMaster,
  legendaryHiker,
  ultimateChallenger,
  perfectYear,
}

/// Category for grouping badges in the UI.
enum BadgeCategory {
  count,
  distance,
  elevation,
  region,
  stamps,
  together,
  time,
  consistency,
  challenge,
  special,
}

/// Immutable badge definition.
class HikingBadge {
  final BadgeType type;
  final BadgeCategory category;
  final String emoji;
  final String titleKo;
  final String titleEn;
  final String descriptionKo;
  final String descriptionEn;

  const HikingBadge({
    required this.type,
    required this.category,
    required this.emoji,
    required this.titleKo,
    required this.titleEn,
    required this.descriptionKo,
    required this.descriptionEn,
  });
}

/// All 100 badge definitions.
const List<HikingBadge> allBadgeDefinitions = [
  // ── 🏃 횟수 (Count) ─ 10 ───────────────────────
  HikingBadge(
    type: BadgeType.firstHike,
    category: BadgeCategory.count,
    emoji: '👣',
    titleKo: '첫걸음',
    titleEn: 'First Step',
    descriptionKo: '첫 번째 등산 기록을 남겨보세요',
    descriptionEn: 'Complete your very first hike',
  ),
  HikingBadge(
    type: BadgeType.hikes5,
    category: BadgeCategory.count,
    emoji: '🥾',
    titleKo: '발걸음',
    titleEn: '5 Hikes',
    descriptionKo: '등산 5회를 달성하세요',
    descriptionEn: 'Complete 5 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes10,
    category: BadgeCategory.count,
    emoji: '🏃',
    titleKo: '열정가',
    titleEn: '10 Hikes',
    descriptionKo: '등산 10회를 달성하세요',
    descriptionEn: 'Complete 10 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes25,
    category: BadgeCategory.count,
    emoji: '🌟',
    titleKo: '산행인',
    titleEn: '25 Hikes',
    descriptionKo: '등산 25회를 달성하세요',
    descriptionEn: 'Complete 25 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes50,
    category: BadgeCategory.count,
    emoji: '🎯',
    titleKo: '등산러',
    titleEn: '50 Hikes',
    descriptionKo: '등산 50회를 달성하세요',
    descriptionEn: 'Complete 50 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes100,
    category: BadgeCategory.count,
    emoji: '💯',
    titleKo: '백전사',
    titleEn: '100 Hikes',
    descriptionKo: '등산 100회를 달성하세요',
    descriptionEn: 'Complete 100 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes200,
    category: BadgeCategory.count,
    emoji: '🏅',
    titleKo: '산마니',
    titleEn: '200 Hikes',
    descriptionKo: '등산 200회를 달성하세요',
    descriptionEn: 'Complete 200 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes365,
    category: BadgeCategory.count,
    emoji: '📆',
    titleKo: '매일산',
    titleEn: '365 Hikes',
    descriptionKo: '등산 365회를 달성하세요',
    descriptionEn: 'Complete 365 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes500,
    category: BadgeCategory.count,
    emoji: '🏆',
    titleKo: '산신령',
    titleEn: '500 Hikes',
    descriptionKo: '등산 500회를 달성하세요',
    descriptionEn: 'Complete 500 hikes',
  ),
  HikingBadge(
    type: BadgeType.hikes1000,
    category: BadgeCategory.count,
    emoji: '👑',
    titleKo: '천봉왕',
    titleEn: '1000 Hikes',
    descriptionKo: '등산 1,000회를 달성하세요',
    descriptionEn: 'Complete 1,000 hikes',
  ),

  // ── 📏 거리 (Distance) ─ 10 ────────────────────
  HikingBadge(
    type: BadgeType.distance10km,
    category: BadgeCategory.distance,
    emoji: '🚶',
    titleKo: '산책꾼',
    titleEn: '10 km',
    descriptionKo: '총 등산 거리 10km를 달성하세요',
    descriptionEn: 'Accumulate 10 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance50km,
    category: BadgeCategory.distance,
    emoji: '🛤️',
    titleKo: '소풍러',
    titleEn: '50 km',
    descriptionKo: '총 등산 거리 50km를 달성하세요',
    descriptionEn: 'Accumulate 50 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance100km,
    category: BadgeCategory.distance,
    emoji: '📏',
    titleKo: '백리길',
    titleEn: '100 km',
    descriptionKo: '총 등산 거리 100km를 달성하세요',
    descriptionEn: 'Accumulate 100 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance200km,
    category: BadgeCategory.distance,
    emoji: '🗺️',
    titleKo: '탐험대',
    titleEn: '200 km',
    descriptionKo: '총 등산 거리 200km를 달성하세요',
    descriptionEn: 'Accumulate 200 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance500km,
    category: BadgeCategory.distance,
    emoji: '🧭',
    titleKo: '오솔길',
    titleEn: '500 km',
    descriptionKo: '총 등산 거리 500km를 달성하세요',
    descriptionEn: 'Accumulate 500 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance1000km,
    category: BadgeCategory.distance,
    emoji: '🌏',
    titleKo: '천리마',
    titleEn: '1,000 km',
    descriptionKo: '총 등산 거리 1,000km를 달성하세요',
    descriptionEn: 'Accumulate 1,000 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance2000km,
    category: BadgeCategory.distance,
    emoji: '✈️',
    titleKo: '대장정',
    titleEn: '2,000 km',
    descriptionKo: '총 등산 거리 2,000km를 달성하세요',
    descriptionEn: 'Accumulate 2,000 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance3000km,
    category: BadgeCategory.distance,
    emoji: '🚀',
    titleKo: '종주왕',
    titleEn: '3,000 km',
    descriptionKo: '총 등산 거리 3,000km를 달성하세요',
    descriptionEn: 'Accumulate 3,000 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance5000km,
    category: BadgeCategory.distance,
    emoji: '🛰️',
    titleKo: '만리행',
    titleEn: '5,000 km',
    descriptionKo: '총 등산 거리 5,000km를 달성하세요',
    descriptionEn: 'Accumulate 5,000 km total hiking distance',
  ),
  HikingBadge(
    type: BadgeType.distance10000km,
    category: BadgeCategory.distance,
    emoji: '🌌',
    titleKo: '무한길',
    titleEn: '10,000 km',
    descriptionKo: '총 등산 거리 10,000km를 달성하세요',
    descriptionEn: 'Accumulate 10,000 km total hiking distance',
  ),

  // ── ⛰️ 고도 (Elevation) ─ 10 ──────────────────
  HikingBadge(
    type: BadgeType.elevation500m,
    category: BadgeCategory.elevation,
    emoji: '⬆️',
    titleKo: '오름길',
    titleEn: '500 m Gain',
    descriptionKo: '총 누적 고도 500m를 달성하세요',
    descriptionEn: 'Accumulate 500 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.elevation1000m,
    category: BadgeCategory.elevation,
    emoji: '🧗',
    titleKo: '천미터',
    titleEn: '1,000 m Gain',
    descriptionKo: '총 누적 고도 1,000m를 달성하세요',
    descriptionEn: 'Accumulate 1,000 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.elevation1500m,
    category: BadgeCategory.elevation,
    emoji: '🪨',
    titleKo: '암벽가',
    titleEn: '1,500 m Gain',
    descriptionKo: '총 누적 고도 1,500m를 달성하세요',
    descriptionEn: 'Accumulate 1,500 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.elevation5000m,
    category: BadgeCategory.elevation,
    emoji: '🏔️',
    titleKo: '고산족',
    titleEn: '5,000 m Gain',
    descriptionKo: '총 누적 고도 5,000m를 달성하세요',
    descriptionEn: 'Accumulate 5,000 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.elevation10000m,
    category: BadgeCategory.elevation,
    emoji: '🦅',
    titleKo: '구름위',
    titleEn: '10,000 m Gain',
    descriptionKo: '총 누적 고도 10,000m를 달성하세요',
    descriptionEn: 'Accumulate 10,000 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.elevation50000m,
    category: BadgeCategory.elevation,
    emoji: '🛸',
    titleKo: '성층권',
    titleEn: '50,000 m Gain',
    descriptionKo: '총 누적 고도 50,000m를 달성하세요',
    descriptionEn: 'Accumulate 50,000 m total elevation gain',
  ),
  HikingBadge(
    type: BadgeType.singleHike500m,
    category: BadgeCategory.elevation,
    emoji: '💪',
    titleKo: '급경사',
    titleEn: 'Single 500 m',
    descriptionKo: '한 번의 등산에서 고도 500m 이상 올라보세요',
    descriptionEn: 'Gain 500 m+ elevation in a single hike',
  ),
  HikingBadge(
    type: BadgeType.singleHike1000m,
    category: BadgeCategory.elevation,
    emoji: '🫡',
    titleKo: '철인왕',
    titleEn: 'Single 1,000 m',
    descriptionKo: '한 번의 등산에서 고도 1,000m 이상 올라보세요',
    descriptionEn: 'Gain 1,000 m+ elevation in a single hike',
  ),
  HikingBadge(
    type: BadgeType.peak1000m,
    category: BadgeCategory.elevation,
    emoji: '⛰️',
    titleKo: '천미봉',
    titleEn: 'Peak 1,000 m',
    descriptionKo: '해발 1,000m 이상의 산 정상에 올라보세요',
    descriptionEn: 'Summit a mountain with altitude 1,000 m+',
  ),
  HikingBadge(
    type: BadgeType.peak1500m,
    category: BadgeCategory.elevation,
    emoji: '🗻',
    titleKo: '고봉정',
    titleEn: 'Peak 1,500 m',
    descriptionKo: '해발 1,500m 이상의 산 정상에 올라보세요',
    descriptionEn: 'Summit a mountain with altitude 1,500 m+',
  ),

  // ── 🗺️ 지역 (Region) ─ 8 ─────────────────────
  HikingBadge(
    type: BadgeType.regions3,
    category: BadgeCategory.region,
    emoji: '📌',
    titleKo: '삼도행',
    titleEn: '3 Regions',
    descriptionKo: '3개 이상의 지역에서 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 3+ different regions',
  ),
  HikingBadge(
    type: BadgeType.regions5,
    category: BadgeCategory.region,
    emoji: '🗾',
    titleKo: '다섯길',
    titleEn: '5 Regions',
    descriptionKo: '5개 이상의 지역에서 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 5+ different regions',
  ),
  HikingBadge(
    type: BadgeType.regions8,
    category: BadgeCategory.region,
    emoji: '🌐',
    titleKo: '팔도행',
    titleEn: '8 Regions',
    descriptionKo: '8개 이상의 지역에서 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 8+ different regions',
  ),
  HikingBadge(
    type: BadgeType.regions10,
    category: BadgeCategory.region,
    emoji: '🧳',
    titleKo: '열지역',
    titleEn: '10 Regions',
    descriptionKo: '10개 이상의 지역에서 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 10+ different regions',
  ),
  HikingBadge(
    type: BadgeType.regions15,
    category: BadgeCategory.region,
    emoji: '🚗',
    titleKo: '전국구',
    titleEn: '15 Regions',
    descriptionKo: '15개 이상의 지역에서 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 15+ different regions',
  ),
  HikingBadge(
    type: BadgeType.allRegions,
    category: BadgeCategory.region,
    emoji: '🇰🇷',
    titleKo: '방방곡',
    titleEn: 'All Regions',
    descriptionKo: '모든 지역의 도장을 최소 1개 이상 모아보세요',
    descriptionEn: 'Collect at least 1 stamp from every region',
  ),
  HikingBadge(
    type: BadgeType.islandMountain,
    category: BadgeCategory.region,
    emoji: '🏝️',
    titleKo: '섬산행',
    titleEn: 'Island Peak',
    descriptionKo: '제주 지역의 산을 올라보세요',
    descriptionEn: 'Hike a mountain in Jeju island region',
  ),
  HikingBadge(
    type: BadgeType.capitalArea5,
    category: BadgeCategory.region,
    emoji: '🏙️',
    titleKo: '수도권',
    titleEn: 'Capital 5',
    descriptionKo: '수도권(서울·경기) 산 5곳의 도장을 모아보세요',
    descriptionEn: 'Collect stamps from 5 mountains in Seoul/Gyeonggi area',
  ),

  // ── 🎖️ 도장 (Stamps) ─ 10 ─────────────────────
  HikingBadge(
    type: BadgeType.stamps5,
    category: BadgeCategory.stamps,
    emoji: '🔰',
    titleKo: '수집가',
    titleEn: '5 Stamps',
    descriptionKo: '도장 5개를 모아보세요',
    descriptionEn: 'Collect 5 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps10,
    category: BadgeCategory.stamps,
    emoji: '🎖️',
    titleKo: '열도장',
    titleEn: '10 Stamps',
    descriptionKo: '도장 10개를 모아보세요',
    descriptionEn: 'Collect 10 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps25,
    category: BadgeCategory.stamps,
    emoji: '🏵️',
    titleKo: '도장통',
    titleEn: '25 Stamps',
    descriptionKo: '도장 25개를 모아보세요',
    descriptionEn: 'Collect 25 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps50,
    category: BadgeCategory.stamps,
    emoji: '🎗️',
    titleKo: '반백장',
    titleEn: '50 Stamps',
    descriptionKo: '도장 50개를 모아보세요',
    descriptionEn: 'Collect 50 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps75,
    category: BadgeCategory.stamps,
    emoji: '🎪',
    titleKo: '칠오장',
    titleEn: '75 Stamps',
    descriptionKo: '도장 75개를 모아보세요',
    descriptionEn: 'Collect 75 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps100,
    category: BadgeCategory.stamps,
    emoji: '💎',
    titleKo: '백도장',
    titleEn: '100 Stamps',
    descriptionKo: '도장 100개를 모아보세요',
    descriptionEn: 'Collect 100 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps150,
    category: BadgeCategory.stamps,
    emoji: '🔮',
    titleKo: '도장왕',
    titleEn: '150 Stamps',
    descriptionKo: '도장 150개를 모아보세요',
    descriptionEn: 'Collect 150 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps200,
    category: BadgeCategory.stamps,
    emoji: '🌠',
    titleKo: '이백장',
    titleEn: '200 Stamps',
    descriptionKo: '도장 200개를 모아보세요',
    descriptionEn: 'Collect 200 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps250,
    category: BadgeCategory.stamps,
    emoji: '🪐',
    titleKo: '도장신',
    titleEn: '250 Stamps',
    descriptionKo: '도장 250개를 모아보세요',
    descriptionEn: 'Collect 250 stamps',
  ),
  HikingBadge(
    type: BadgeType.stamps300,
    category: BadgeCategory.stamps,
    emoji: '☄️',
    titleKo: '삼백장',
    titleEn: '300 Stamps',
    descriptionKo: '도장 300개를 모아보세요',
    descriptionEn: 'Collect 300 stamps',
  ),

  // ── 🤝 함께 (Together) ─ 8 ────────────────────
  HikingBadge(
    type: BadgeType.together1,
    category: BadgeCategory.together,
    emoji: '🤝',
    titleKo: '첫동행',
    titleEn: 'First Together',
    descriptionKo: '첫 함께 도장을 받아보세요',
    descriptionEn: 'Earn your first together stamp',
  ),
  HikingBadge(
    type: BadgeType.together5,
    category: BadgeCategory.together,
    emoji: '👫',
    titleKo: '단짝산',
    titleEn: '5 Together',
    descriptionKo: '함께 도장 5개를 모아보세요',
    descriptionEn: 'Collect 5 together stamps',
  ),
  HikingBadge(
    type: BadgeType.together10,
    category: BadgeCategory.together,
    emoji: '💑',
    titleKo: '산우정',
    titleEn: '10 Together',
    descriptionKo: '함께 도장 10개를 모아보세요',
    descriptionEn: 'Collect 10 together stamps',
  ),
  HikingBadge(
    type: BadgeType.together25,
    category: BadgeCategory.together,
    emoji: '🫂',
    titleKo: '동반자',
    titleEn: '25 Together',
    descriptionKo: '함께 도장 25개를 모아보세요',
    descriptionEn: 'Collect 25 together stamps',
  ),
  HikingBadge(
    type: BadgeType.together50,
    category: BadgeCategory.together,
    emoji: '👨‍👩‍👧',
    titleKo: '가족산',
    titleEn: '50 Together',
    descriptionKo: '함께 도장 50개를 모아보세요',
    descriptionEn: 'Collect 50 together stamps',
  ),
  HikingBadge(
    type: BadgeType.together100,
    category: BadgeCategory.together,
    emoji: '💞',
    titleKo: '백년산',
    titleEn: '100 Together',
    descriptionKo: '함께 도장 100개를 모아보세요',
    descriptionEn: 'Collect 100 together stamps',
  ),
  HikingBadge(
    type: BadgeType.togetherStreak3,
    category: BadgeCategory.together,
    emoji: '🔗',
    titleKo: '삼연속',
    titleEn: 'Together 3 Streak',
    descriptionKo: '연속 3회 함께 도장을 받아보세요',
    descriptionEn: 'Get 3 consecutive together stamps',
  ),
  HikingBadge(
    type: BadgeType.togetherStreak7,
    category: BadgeCategory.together,
    emoji: '⛓️',
    titleKo: '칠연속',
    titleEn: 'Together 7 Streak',
    descriptionKo: '연속 7회 함께 도장을 받아보세요',
    descriptionEn: 'Get 7 consecutive together stamps',
  ),

  // ── ⏰ 시간 (Time) ─ 10 ───────────────────────
  HikingBadge(
    type: BadgeType.earlyBird,
    category: BadgeCategory.time,
    emoji: '🐓',
    titleKo: '얼리버드',
    titleEn: 'Early Bird',
    descriptionKo: '오전 6시 이전에 등산을 시작해보세요',
    descriptionEn: 'Start a hike before 6 AM',
  ),
  HikingBadge(
    type: BadgeType.dawnHiker,
    category: BadgeCategory.time,
    emoji: '🌅',
    titleKo: '새벽산',
    titleEn: 'Dawn Hiker',
    descriptionKo: '오전 5시 이전에 등산을 시작해보세요',
    descriptionEn: 'Start a hike before 5 AM',
  ),
  HikingBadge(
    type: BadgeType.nightHiker,
    category: BadgeCategory.time,
    emoji: '🌙',
    titleKo: '야간산',
    titleEn: 'Night Hiker',
    descriptionKo: '오후 8시 이후에 등산을 시작해보세요',
    descriptionEn: 'Start a hike after 8 PM',
  ),
  HikingBadge(
    type: BadgeType.longHike4h,
    category: BadgeCategory.time,
    emoji: '⏱️',
    titleKo: '장거리',
    titleEn: 'Long Hike 4h',
    descriptionKo: '4시간 이상 등산해보세요',
    descriptionEn: 'Complete a hike lasting 4+ hours',
  ),
  HikingBadge(
    type: BadgeType.longHike6h,
    category: BadgeCategory.time,
    emoji: '⌛',
    titleKo: '대장정',
    titleEn: 'Long Hike 6h',
    descriptionKo: '6시간 이상 등산해보세요',
    descriptionEn: 'Complete a hike lasting 6+ hours',
  ),
  HikingBadge(
    type: BadgeType.longHike8h,
    category: BadgeCategory.time,
    emoji: '🕗',
    titleKo: '종일산',
    titleEn: 'Long Hike 8h',
    descriptionKo: '8시간 이상 등산해보세요',
    descriptionEn: 'Complete a hike lasting 8+ hours',
  ),
  HikingBadge(
    type: BadgeType.longHike10h,
    category: BadgeCategory.time,
    emoji: '🕙',
    titleKo: '철인행',
    titleEn: 'Long Hike 10h',
    descriptionKo: '10시간 이상 등산해보세요',
    descriptionEn: 'Complete a hike lasting 10+ hours',
  ),
  HikingBadge(
    type: BadgeType.quickHike1h,
    category: BadgeCategory.time,
    emoji: '⚡',
    titleKo: '번개산',
    titleEn: 'Quick Hike',
    descriptionKo: '1시간 이내에 등산을 완료해보세요',
    descriptionEn: 'Complete a hike in under 1 hour',
  ),
  HikingBadge(
    type: BadgeType.sunriseHike,
    category: BadgeCategory.time,
    emoji: '🌄',
    titleKo: '일출행',
    titleEn: 'Sunrise Hike',
    descriptionKo: '오전 5~7시 사이에 등산을 시작해보세요',
    descriptionEn: 'Start a hike between 5-7 AM',
  ),
  HikingBadge(
    type: BadgeType.sunsetHike,
    category: BadgeCategory.time,
    emoji: '🌇',
    titleKo: '일몰행',
    titleEn: 'Sunset Hike',
    descriptionKo: '오후 5~7시 사이에 등산을 시작해보세요',
    descriptionEn: 'Start a hike between 5-7 PM',
  ),

  // ── 📅 꾸준함 (Consistency) ─ 10 ──────────────
  HikingBadge(
    type: BadgeType.streakWeek,
    category: BadgeCategory.consistency,
    emoji: '🔥',
    titleKo: '일주행',
    titleEn: 'Week Streak',
    descriptionKo: '7일 연속 등산해보세요',
    descriptionEn: 'Hike 7 consecutive days',
  ),
  HikingBadge(
    type: BadgeType.streak2weeks,
    category: BadgeCategory.consistency,
    emoji: '🔥',
    titleKo: '이주행',
    titleEn: '2-Week Streak',
    descriptionKo: '14일 연속 등산해보세요',
    descriptionEn: 'Hike 14 consecutive days',
  ),
  HikingBadge(
    type: BadgeType.streak30days,
    category: BadgeCategory.consistency,
    emoji: '🔥',
    titleKo: '한달행',
    titleEn: '30-Day Streak',
    descriptionKo: '30일 연속 등산해보세요',
    descriptionEn: 'Hike 30 consecutive days',
  ),
  HikingBadge(
    type: BadgeType.monthlyChallenger,
    category: BadgeCategory.consistency,
    emoji: '📅',
    titleKo: '월간행',
    titleEn: 'Monthly 4',
    descriptionKo: '한 달에 4회 이상 등산해보세요',
    descriptionEn: 'Hike 4+ times in a single month',
  ),
  HikingBadge(
    type: BadgeType.monthly8,
    category: BadgeCategory.consistency,
    emoji: '🗓️',
    titleKo: '월팔행',
    titleEn: 'Monthly 8',
    descriptionKo: '한 달에 8회 이상 등산해보세요',
    descriptionEn: 'Hike 8+ times in a single month',
  ),
  HikingBadge(
    type: BadgeType.yearlyHiker,
    category: BadgeCategory.consistency,
    emoji: '🎄',
    titleKo: '연간행',
    titleEn: 'Yearly 12',
    descriptionKo: '한 해에 12회 이상 등산해보세요',
    descriptionEn: 'Hike 12+ times in a single year',
  ),
  HikingBadge(
    type: BadgeType.yearly50,
    category: BadgeCategory.consistency,
    emoji: '🎆',
    titleKo: '연오십',
    titleEn: 'Yearly 50',
    descriptionKo: '한 해에 50회 이상 등산해보세요',
    descriptionEn: 'Hike 50+ times in a single year',
  ),
  HikingBadge(
    type: BadgeType.yearly100,
    category: BadgeCategory.consistency,
    emoji: '🎇',
    titleKo: '연백행',
    titleEn: 'Yearly 100',
    descriptionKo: '한 해에 100회 이상 등산해보세요',
    descriptionEn: 'Hike 100+ times in a single year',
  ),
  HikingBadge(
    type: BadgeType.allSeasons,
    category: BadgeCategory.consistency,
    emoji: '🍂',
    titleKo: '사계절',
    titleEn: 'All Seasons',
    descriptionKo: '봄·여름·가을·겨울 모두 등산해보세요',
    descriptionEn: 'Hike in all four seasons',
  ),
  HikingBadge(
    type: BadgeType.everyMonth,
    category: BadgeCategory.consistency,
    emoji: '🗃️',
    titleKo: '열두달',
    titleEn: 'Every Month',
    descriptionKo: '12개월 모두 한 번 이상 등산해보세요 (연도 무관)',
    descriptionEn: 'Hike at least once in each of the 12 months (any year)',
  ),

  // ── 💪 도전 (Challenge) ─ 10 ──────────────────
  HikingBadge(
    type: BadgeType.weekendWarrior,
    category: BadgeCategory.challenge,
    emoji: '🦸',
    titleKo: '주말전사',
    titleEn: 'Weekend Warrior',
    descriptionKo: '주말(토·일)에 10회 이상 등산해보세요',
    descriptionEn: 'Complete 10+ hikes on weekends (Sat/Sun)',
  ),
  HikingBadge(
    type: BadgeType.weekdayHiker,
    category: BadgeCategory.challenge,
    emoji: '💼',
    titleKo: '평일러',
    titleEn: 'Weekday Hiker',
    descriptionKo: '평일(월~금)에 10회 이상 등산해보세요',
    descriptionEn: 'Complete 10+ hikes on weekdays (Mon-Fri)',
  ),
  HikingBadge(
    type: BadgeType.rainHiker,
    category: BadgeCategory.challenge,
    emoji: '🌧️',
    titleKo: '우중산',
    titleEn: 'Rain Hiker',
    descriptionKo: '비 오는 날 등산 기록을 남겨보세요 (6~8월)',
    descriptionEn: 'Complete a hike during rainy season (Jun-Aug)',
  ),
  HikingBadge(
    type: BadgeType.winterHiker,
    category: BadgeCategory.challenge,
    emoji: '❄️',
    titleKo: '설산행',
    titleEn: 'Winter Hiker',
    descriptionKo: '겨울(12~2월)에 등산해보세요',
    descriptionEn: 'Complete a hike in winter (Dec-Feb)',
  ),
  HikingBadge(
    type: BadgeType.summerHiker,
    category: BadgeCategory.challenge,
    emoji: '☀️',
    titleKo: '한여름',
    titleEn: 'Summer Hiker',
    descriptionKo: '여름(6~8월)에 등산해보세요',
    descriptionEn: 'Complete a hike in summer (Jun-Aug)',
  ),
  HikingBadge(
    type: BadgeType.speedDemon,
    category: BadgeCategory.challenge,
    emoji: '🏎️',
    titleKo: '쾌속행',
    titleEn: 'Speed Demon',
    descriptionKo: '5km 이상을 2시간 이내에 완료해보세요',
    descriptionEn: 'Complete a 5+ km hike in under 2 hours',
  ),
  HikingBadge(
    type: BadgeType.distanceDay20km,
    category: BadgeCategory.challenge,
    emoji: '🦶',
    titleKo: '이십킬',
    titleEn: '20 km Day',
    descriptionKo: '하루에 20km 이상 등산해보세요',
    descriptionEn: 'Hike 20+ km in a single day',
  ),
  HikingBadge(
    type: BadgeType.multiPeak3,
    category: BadgeCategory.challenge,
    emoji: '🏔️',
    titleKo: '삼봉행',
    titleEn: 'Multi-Peak 3',
    descriptionKo: '하루에 3개 이상의 산을 올라보세요',
    descriptionEn: 'Summit 3+ different mountains in a single day',
  ),
  HikingBadge(
    type: BadgeType.backToBack,
    category: BadgeCategory.challenge,
    emoji: '🔄',
    titleKo: '연속행',
    titleEn: 'Back to Back',
    descriptionKo: '이틀 연속 다른 산에 올라보세요',
    descriptionEn: 'Hike different mountains on 2 consecutive days',
  ),
  HikingBadge(
    type: BadgeType.centurion,
    category: BadgeCategory.challenge,
    emoji: '🛡️',
    titleKo: '백전백승',
    titleEn: 'Centurion',
    descriptionKo: '100가지 다른 산에 올라보세요',
    descriptionEn: 'Summit 100 different mountains',
  ),

  // ── 🌟 특수 (Special) ─ 14 ────────────────────
  HikingBadge(
    type: BadgeType.newYear,
    category: BadgeCategory.special,
    emoji: '🎍',
    titleKo: '해맞이',
    titleEn: 'New Year Hike',
    descriptionKo: '1월 1일에 등산해보세요',
    descriptionEn: 'Hike on January 1st',
  ),
  HikingBadge(
    type: BadgeType.springBloom,
    category: BadgeCategory.special,
    emoji: '🌸',
    titleKo: '봄나들',
    titleEn: 'Spring Bloom',
    descriptionKo: '봄(3~5월)에 5회 이상 등산해보세요',
    descriptionEn: 'Hike 5+ times in spring (Mar-May)',
  ),
  HikingBadge(
    type: BadgeType.summerSolstice,
    category: BadgeCategory.special,
    emoji: '🌻',
    titleKo: '하지행',
    titleEn: 'Summer Solstice',
    descriptionKo: '6월 21일 전후(6/20~6/22)에 등산해보세요',
    descriptionEn: 'Hike around June 21 (Jun 20-22)',
  ),
  HikingBadge(
    type: BadgeType.autumnLeaves,
    category: BadgeCategory.special,
    emoji: '🍁',
    titleKo: '단풍행',
    titleEn: 'Autumn Leaves',
    descriptionKo: '가을(9~11월)에 5회 이상 등산해보세요',
    descriptionEn: 'Hike 5+ times in autumn (Sep-Nov)',
  ),
  HikingBadge(
    type: BadgeType.winterSolstice,
    category: BadgeCategory.special,
    emoji: '🎄',
    titleKo: '동지행',
    titleEn: 'Winter Solstice',
    descriptionKo: '12월 21일 전후(12/20~12/22)에 등산해보세요',
    descriptionEn: 'Hike around December 21 (Dec 20-22)',
  ),
  HikingBadge(
    type: BadgeType.fullMoon,
    category: BadgeCategory.special,
    emoji: '🌕',
    titleKo: '보름행',
    titleEn: 'Full Moon',
    descriptionKo: '보름달(음력 15일 전후)에 등산해보세요 — 매월 15일',
    descriptionEn: 'Hike on the 15th of any month',
  ),
  HikingBadge(
    type: BadgeType.birthday,
    category: BadgeCategory.special,
    emoji: '🎂',
    titleKo: '생일산',
    titleEn: 'Birthday Hike',
    descriptionKo: '본인 생일에 등산해보세요 (프로필 생일 기준)',
    descriptionEn: 'Hike on your birthday (based on profile)',
  ),
  HikingBadge(
    type: BadgeType.anniversary100,
    category: BadgeCategory.special,
    emoji: '🎊',
    titleKo: '백일산',
    titleEn: '100th Day',
    descriptionKo: '앱 사용 100일째 되는 날에 등산해보세요',
    descriptionEn: 'Hike on the 100th day since joining the app',
  ),
  HikingBadge(
    type: BadgeType.milestone50stamps,
    category: BadgeCategory.special,
    emoji: '🏛️',
    titleKo: '오십도',
    titleEn: '50 Stamps Milestone',
    descriptionKo: '도장 50개를 달성한 기념 뱃지',
    descriptionEn: 'Milestone badge for reaching 50 stamps',
  ),
  HikingBadge(
    type: BadgeType.explorer20regions,
    category: BadgeCategory.special,
    emoji: '🧭',
    titleKo: '대탐험',
    titleEn: '20 Regions Explorer',
    descriptionKo: '20개 이상의 지역에서 등산해보세요',
    descriptionEn: 'Hike in 20+ different regions',
  ),
  HikingBadge(
    type: BadgeType.grandMaster,
    category: BadgeCategory.special,
    emoji: '🎖️',
    titleKo: '대사범',
    titleEn: 'Grand Master',
    descriptionKo: '50개 이상의 뱃지를 획득하세요',
    descriptionEn: 'Earn 50+ badges',
  ),
  HikingBadge(
    type: BadgeType.legendaryHiker,
    category: BadgeCategory.special,
    emoji: '🐉',
    titleKo: '전설행',
    titleEn: 'Legendary Hiker',
    descriptionKo: '75개 이상의 뱃지를 획득하세요',
    descriptionEn: 'Earn 75+ badges',
  ),
  HikingBadge(
    type: BadgeType.ultimateChallenger,
    category: BadgeCategory.special,
    emoji: '🏆',
    titleKo: '궁극자',
    titleEn: 'Ultimate Challenger',
    descriptionKo: '90개 이상의 뱃지를 획득하세요',
    descriptionEn: 'Earn 90+ badges',
  ),
  HikingBadge(
    type: BadgeType.perfectYear,
    category: BadgeCategory.special,
    emoji: '✨',
    titleKo: '완벽년',
    titleEn: 'Perfect Year',
    descriptionKo: '한 해 동안 매월 1회 이상 등산하고 총 50회를 달성하세요',
    descriptionEn: 'Hike 50+ times in one year with at least 1 hike every month',
  ),
];
