import 'package:flutter/material.dart';

enum Difficulty {
  beginner('초급'),
  intermediate('중급'),
  advanced('상급');

  final String label;
  const Difficulty(this.label);

  Color get color {
    return switch (this) {
      Difficulty.beginner => Colors.green,
      Difficulty.intermediate => Colors.orange,
      Difficulty.advanced => Colors.red,
    };
  }

  static Difficulty fromLabel(String label) {
    // 백엔드: easy/mid/hard, 로컬: 초급/중급/상급
    const map = {'easy': '초급', 'mid': '중급', 'hard': '상급'};
    final mapped = map[label] ?? label;
    return Difficulty.values.firstWhere(
      (d) => d.label == mapped,
      orElse: () => Difficulty.intermediate,
    );
  }
}

class Mountain {
  final String id;
  final String name;
  final String location;
  final Difficulty difficulty;
  final String time;
  final double distanceKm;
  final int height;
  final String emoji;
  final List<Color> colors;
  final String description;
  final double latitude;
  final double longitude;
  final String? imageUrl;
  final List<Map<String, dynamic>> courses;

  const Mountain({
    required this.id,
    required this.name,
    required this.location,
    required this.difficulty,
    required this.time,
    required this.distanceKm,
    required this.height,
    required this.emoji,
    required this.colors,
    required this.description,
    required this.latitude,
    required this.longitude,
    this.imageUrl,
    this.courses = const [],
  });

  String get distance => '${distanceKm}km';

  Map<String, dynamic> toJson() => {
    'id': id,
    'name': name,
    'location': location,
    'difficulty': difficulty.label,
    'time': time,
    'distanceKm': distanceKm,
    'height': height,
    'emoji': emoji,
    'colors': colors.map((c) => c.toARGB32()).toList(),
    'description': description,
    'latitude': latitude,
    'longitude': longitude,
    'imageUrl': imageUrl,
    if (courses.isNotEmpty) 'courses': courses,
  };

  factory Mountain.fromJson(Map<String, dynamic> json) {
    final distanceKm = json['distanceKm'] != null
        ? (json['distanceKm'] as num).toDouble()
        : double.tryParse((json['distance'] as String? ?? '').replaceAll(RegExp(r'[^0-9.]'), '')) ?? 0;

    // 백엔드: lat/lng (string), region / 로컬: latitude/longitude (num), location
    final lat = json['latitude'] ?? json['lat'];
    final lng = json['longitude'] ?? json['lng'];

    return Mountain(
      id: json['id']?.toString() ?? '',
      name: json['name'] ?? '',
      location: json['location'] ?? json['region'] ?? '',
      difficulty: Difficulty.fromLabel(json['difficulty'] ?? '중급'),
      time: json['time'] ?? '',
      distanceKm: distanceKm,
      height: json['height'] ?? 0,
      emoji: _validMountainEmoji(json['emoji']),
      colors: json['colors'] != null
          ? (json['colors'] as List).map((c) => Color(c as int)).toList()
          : [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
      description: json['description'] ?? '',
      latitude: lat != null ? double.tryParse(lat.toString()) ?? 0 : 0,
      longitude: lng != null ? double.tryParse(lng.toString()) ?? 0 : 0,
      imageUrl: json['imageUrl'] ?? json['thumbnail'],
      courses: json['courses'] is List
          ? (json['courses'] as List).map((c) => Map<String, dynamic>.from(c as Map)).toList()
          : [],
    );
  }

  static const _mountainEmojis = {'🏔️', '⛰️', '🌲', '🗻', '🏞️'};

  static String _validMountainEmoji(String? emoji) {
    if (emoji == null || emoji.isEmpty) return '🏔️';
    if (_mountainEmojis.contains(emoji)) return emoji;
    return '🏔️';
  }
}

final List<Mountain> defaultMountains = [
  // 1. 가리산
  Mountain(
    id: 'mt_1',
    name: '가리산',
    location: '강원 홍천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1051,
    emoji: '🏔️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '홍천의 대표 명산으로, 울창한 원시림과 기암괴석이 어우러져 사계절 아름다운 경치를 자랑합니다.',
    latitude: 37.8847,
    longitude: 128.0567,
  ),
  // 2. 가리왕산
  Mountain(
    id: 'mt_2',
    name: '가리왕산',
    location: '강원 정선/평창',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1561,
    emoji: '⛰️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '천년 주목 군락지와 원시림이 보존된 산으로, 2018 평창 동계올림픽 알파인 스키 경기장이 위치했습니다.',
    latitude: 37.4617,
    longitude: 128.5633,
  ),
  // 3. 가야산
  Mountain(
    id: 'mt_3',
    name: '가야산',
    location: '경남 합천/경북 성주',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 11.0,
    height: 1430,
    emoji: '🌲',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '해인사와 팔만대장경을 품은 산으로, 상왕봉 정상의 우뚝 솟은 바위가 장관입니다.',
    latitude: 35.8167,
    longitude: 128.1000,
  ),
  // 4. 감악산
  Mountain(
    id: 'mt_4',
    name: '감악산',
    location: '경기 파주/연천',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 675,
    emoji: '🗻',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '경기 북부의 명산으로 임꺽정의 전설이 깃든 곳이며, 가을 억새밭이 특히 아름답습니다.',
    latitude: 37.9417,
    longitude: 126.9567,
  ),
  // 5. 강천산
  Mountain(
    id: 'mt_5',
    name: '강천산',
    location: '전북 순창',
    difficulty: Difficulty.beginner,
    time: '약 3시간',
    distanceKm: 5.0,
    height: 584,
    emoji: '🌲',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '한국 최초의 군립공원으로, 가을 단풍과 현수교가 유명하며 계곡미가 뛰어납니다.',
    latitude: 35.4167,
    longitude: 127.0167,
  ),
  // 6. 계룡산
  Mountain(
    id: 'mt_6',
    name: '계룡산',
    location: '충남 공주/논산',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 845,
    emoji: '⛰️',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '닭의 벼슬을 닮은 용의 형상에서 이름이 유래했으며, 동학사와 갑사 등 유서 깊은 사찰이 있습니다.',
    latitude: 36.3500,
    longitude: 127.2000,
  ),
  // 7. 계방산
  Mountain(
    id: 'mt_7',
    name: '계방산',
    location: '강원 홍천/평창',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.5,
    height: 1577,
    emoji: '🏞️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '한라산, 지리산, 설악산에 이어 남한에서 네 번째로 높은 산으로, 운해와 상고대가 장관입니다.',
    latitude: 37.7333,
    longitude: 128.4667,
  ),
  // 8. 공작산
  Mountain(
    id: 'mt_8',
    name: '공작산',
    location: '강원 홍천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 887,
    emoji: '🗻',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '산의 형상이 공작이 날개를 펼친 모습과 닮아 이름 붙여졌으며, 수타사 계곡이 유명합니다.',
    latitude: 37.7833,
    longitude: 127.9833,
  ),
  // 9. 관악산
  Mountain(
    id: 'mt_9',
    name: '관악산',
    location: '서울 관악',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.8,
    height: 629,
    emoji: '🏔️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '서울대학교 뒤편에 솟아있는 서울의 대표적 명산으로, 연주대에서 바라보는 일몰이 장관입니다.',
    latitude: 37.4331,
    longitude: 126.9637,
  ),
  // 10. 구병산
  Mountain(
    id: 'mt_10',
    name: '구병산',
    location: '충북 보은',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 876,
    emoji: '⛰️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '아홉 개의 봉우리가 병풍처럼 펼쳐져 이름 붙여졌으며, 속리산 국립공원 자락에 위치합니다.',
    latitude: 36.4667,
    longitude: 127.7833,
  ),
  // 11. 금산
  Mountain(
    id: 'mt_11',
    name: '금산',
    location: '경남 남해',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 5.5,
    height: 681,
    emoji: '🌲',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '남해 바다를 한눈에 조망할 수 있는 산으로, 보리암에서의 일출이 한국 3대 기도처로 유명합니다.',
    latitude: 34.7333,
    longitude: 127.9833,
  ),
  // 12. 금수산
  Mountain(
    id: 'mt_12',
    name: '금수산',
    location: '충북 제천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1016,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '충주호를 굽어보는 절경이 뛰어나며, 얼음골과 용담폭포 등 볼거리가 풍부합니다.',
    latitude: 36.9333,
    longitude: 128.1167,
  ),
  // 13. 금오산
  Mountain(
    id: 'mt_13',
    name: '금오산',
    location: '경북 구미',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 976,
    emoji: '🌲',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '구미를 대표하는 산으로 대혜폭포와 해운사가 있으며, 케이블카로도 오를 수 있습니다.',
    latitude: 36.1167,
    longitude: 128.3333,
  ),
  // 14. 금정산
  Mountain(
    id: 'mt_14',
    name: '금정산',
    location: '부산 금정',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 801,
    emoji: '⛰️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '부산의 진산으로 금정산성과 범어사가 있으며, 도심에서 가까워 시민들이 즐겨 찾습니다.',
    latitude: 35.2833,
    longitude: 129.0667,
  ),
  // 15. 깃대봉
  Mountain(
    id: 'mt_15',
    name: '깃대봉',
    location: '전남 신안 홍도',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 3.5,
    height: 368,
    emoji: '🏞️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '다도해해상국립공원 홍도의 최고봉으로, 기암절벽과 동백나무 군락이 아름답습니다.',
    latitude: 34.6833,
    longitude: 125.1833,
  ),
  // 16. 남산
  Mountain(
    id: 'mt_16',
    name: '남산',
    location: '경북 경주',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 4.0,
    height: 468,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '신라 천년의 역사가 숨 쉬는 노천 박물관으로, 수많은 불상과 석탑이 산 곳곳에 남아 있습니다.',
    latitude: 35.7833,
    longitude: 129.2167,
  ),
  // 17. 내연산
  Mountain(
    id: 'mt_17',
    name: '내연산',
    location: '경북 포항',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 710,
    emoji: '🏔️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '보경사에서 이어지는 12폭포 계곡이 장관이며, 여름 피서지로도 인기가 높습니다.',
    latitude: 36.2000,
    longitude: 129.2167,
  ),
  // 18. 내장산
  Mountain(
    id: 'mt_18',
    name: '내장산',
    location: '전북 정읍',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 763,
    emoji: '⛰️',
    colors: [const Color(0xFFE76F51), const Color(0xFF9B2226)],
    description: '한국 최고의 단풍 명소로, 가을이면 내장사 진입로의 단풍터널이 절경을 이룹니다.',
    latitude: 35.4833,
    longitude: 126.9000,
  ),
  // 19. 덕숭산
  Mountain(
    id: 'mt_19',
    name: '덕숭산',
    location: '충남 예산',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 4.5,
    height: 495,
    emoji: '🌲',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '수덕사를 품고 있는 산으로, 수덕사 대웅전은 한국에서 가장 오래된 목조건물 중 하나입니다.',
    latitude: 36.6500,
    longitude: 126.6333,
  ),
  // 20. 덕유산
  Mountain(
    id: 'mt_20',
    name: '덕유산',
    location: '전북 무주/경남 거창',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 12.0,
    height: 1614,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '향적봉 정상의 상고대와 겨울 설경이 유명하며, 무주리조트 곤돌라로도 접근 가능합니다.',
    latitude: 35.8500,
    longitude: 127.7500,
  ),
  // 21. 덕항산
  Mountain(
    id: 'mt_21',
    name: '덕항산',
    location: '강원 삼척/태백',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1071,
    emoji: '🌲',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '환선굴, 대금굴 등 천연 석회동굴이 산재한 산으로, 카르스트 지형이 독특합니다.',
    latitude: 37.2167,
    longitude: 129.0167,
  ),
  // 22. 도락산
  Mountain(
    id: 'mt_22',
    name: '도락산',
    location: '충북 단양',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 6.5,
    height: 964,
    emoji: '⛰️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '단양팔경 중 하나인 상선암, 중선암, 하선암을 품고 있으며, 남한강 조망이 뛰어납니다.',
    latitude: 36.9833,
    longitude: 128.3000,
  ),
  // 23. 두륜산
  Mountain(
    id: 'mt_23',
    name: '두륜산',
    location: '전남 해남',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 703,
    emoji: '🏞️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '대흥사를 품은 남도의 명산으로, 한반도 최남단 땅끝마을과 가까워 상징적 의미가 큽니다.',
    latitude: 34.4833,
    longitude: 126.6333,
  ),
  // 24. 두타산
  Mountain(
    id: 'mt_24',
    name: '두타산',
    location: '강원 삼척/동해',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.5,
    height: 1353,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '베틀바위, 쌍폭포 등 기암과 폭포가 어우러진 산으로, 무릉계곡의 절경이 유명합니다.',
    latitude: 37.2833,
    longitude: 129.0333,
  ),
  // 25. 마니산
  Mountain(
    id: 'mt_25',
    name: '마니산',
    location: '인천 강화',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 4.0,
    height: 472,
    emoji: '🏔️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '단군이 하늘에 제사를 지낸 참성단이 있는 민족의 영산으로, 전국체전 성화 채화지입니다.',
    latitude: 37.6167,
    longitude: 126.4333,
  ),
  // 26. 마이산
  Mountain(
    id: 'mt_26',
    name: '마이산',
    location: '전북 진안',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 5.5,
    height: 686,
    emoji: '⛰️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '말의 귀를 닮은 두 봉우리가 독특하며, 탑사의 돌탑군은 신비로운 분위기를 자아냅니다.',
    latitude: 35.7667,
    longitude: 127.4167,
  ),
  // 27. 명성산
  Mountain(
    id: 'mt_27',
    name: '명성산',
    location: '경기 포천/강원 철원',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 923,
    emoji: '🌲',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '궁예의 전설이 깃든 산으로, 가을 억새 군락지가 장관이며 산정호수와 연계 등산이 가능합니다.',
    latitude: 38.0833,
    longitude: 127.3333,
  ),
  // 28. 명지산
  Mountain(
    id: 'mt_28',
    name: '명지산',
    location: '경기 가평',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.0,
    height: 1267,
    emoji: '🗻',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '경기도 최고봉으로, 깊은 계곡과 울창한 숲이 어우러져 자연 그대로의 아름다움을 간직하고 있습니다.',
    latitude: 37.9500,
    longitude: 127.3667,
  ),
  // 29. 모악산
  Mountain(
    id: 'mt_29',
    name: '모악산',
    location: '전북 전주/김제',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 794,
    emoji: '🌲',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '금산사를 품고 있는 호남의 명산으로, 미륵전의 웅장함과 사계절 아름다운 풍광이 자랑입니다.',
    latitude: 35.7333,
    longitude: 127.0833,
  ),
  // 30. 무등산
  Mountain(
    id: 'mt_30',
    name: '무등산',
    location: '광주/전남 화순/담양',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.5,
    height: 1187,
    emoji: '⛰️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '광주의 상징이자 주상절리 서석대·입석대가 천연기념물로 지정된 국립공원입니다.',
    latitude: 35.1333,
    longitude: 126.9833,
  ),
  // 31. 무학산
  Mountain(
    id: 'mt_31',
    name: '무학산',
    location: '경남 마산',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 761,
    emoji: '🏞️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '마산만과 창원 시가지를 한눈에 내려다볼 수 있는 산으로, 학이 춤추는 형상을 닮았습니다.',
    latitude: 35.2000,
    longitude: 128.5833,
  ),
  // 32. 미륵산
  Mountain(
    id: 'mt_32',
    name: '미륵산',
    location: '경남 통영',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 4.5,
    height: 461,
    emoji: '🗻',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '한려수도의 절경을 360도 파노라마로 감상할 수 있으며, 케이블카로 쉽게 오를 수 있습니다.',
    latitude: 34.8167,
    longitude: 128.4167,
  ),
  // 33. 민주지산
  Mountain(
    id: 'mt_33',
    name: '민주지산',
    location: '충북 영동/전북 무주',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1242,
    emoji: '🏔️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '충북 최고봉으로, 물한계곡의 시원한 물줄기와 울창한 원시림이 잘 보존되어 있습니다.',
    latitude: 35.9333,
    longitude: 127.8833,
  ),
  // 34. 방장산
  Mountain(
    id: 'mt_34',
    name: '방장산',
    location: '전북 고창/전남 장성',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 743,
    emoji: '⛰️',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '호남정맥의 중심 산으로, 편백나무 숲이 우거져 산림욕 명소로 사랑받고 있습니다.',
    latitude: 35.4667,
    longitude: 126.8833,
  ),
  // 35. 방태산
  Mountain(
    id: 'mt_35',
    name: '방태산',
    location: '강원 인제',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 11.0,
    height: 1444,
    emoji: '🌲',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '적가리골의 원시림이 유명하며, 자연 생태계가 잘 보존된 오지 산행지로 알려져 있습니다.',
    latitude: 37.9167,
    longitude: 128.3167,
  ),
  // 36. 백덕산
  Mountain(
    id: 'mt_36',
    name: '백덕산',
    location: '강원 영월/평창',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.5,
    height: 1350,
    emoji: '🗻',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '강원도 영월과 평창 경계에 위치하며, 겨울 설화와 조망이 뛰어난 비경의 산입니다.',
    latitude: 37.3500,
    longitude: 128.5500,
  ),
  // 37. 백암산
  Mountain(
    id: 'mt_37',
    name: '백암산',
    location: '전남 장성',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 741,
    emoji: '🌲',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '내장산 국립공원의 남쪽 봉우리로, 백양사와 비자나무 숲이 아름답습니다.',
    latitude: 35.4500,
    longitude: 126.8833,
  ),
  // 38. 백운산 (광양)
  Mountain(
    id: 'mt_38',
    name: '백운산 (광양)',
    location: '전남 광양',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1218,
    emoji: '⛰️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '전남에서 가장 높은 산으로, 봄철 매화축제와 억불봉의 조망이 유명합니다.',
    latitude: 35.1167,
    longitude: 127.6167,
  ),
  // 39. 백운산 (포천)
  Mountain(
    id: 'mt_39',
    name: '백운산 (포천)',
    location: '경기 포천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 904,
    emoji: '🏞️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '흰 구름이 산정에 걸린다 하여 이름 붙여졌으며, 광덕고개에서 출발하는 코스가 인기입니다.',
    latitude: 37.9833,
    longitude: 127.1000,
  ),
  // 40. 북한산
  Mountain(
    id: 'mt_40',
    name: '북한산',
    location: '서울',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 9.2,
    height: 836,
    emoji: '🗻',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '서울의 상징적인 국립공원으로, 백운대 정상에서 서울 전경을 한눈에 조망할 수 있습니다.',
    latitude: 37.6584,
    longitude: 126.9780,
  ),
  // 41. 비슬산
  Mountain(
    id: 'mt_41',
    name: '비슬산',
    location: '대구 달성',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 1084,
    emoji: '🏔️',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '봄이면 정상 일대에 참꽃 군락지가 장관을 이루며, 대견사지 삼층석탑이 유명합니다.',
    latitude: 35.7167,
    longitude: 128.5500,
  ),
  // 42. 사량도 지리산
  Mountain(
    id: 'mt_42',
    name: '사량도 지리산',
    location: '경남 통영 사량도',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 3.5,
    height: 398,
    emoji: '⛰️',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '통영 사량도의 최고봉으로, 남해 다도해의 아름다운 섬들을 조망할 수 있는 해상 명산입니다.',
    latitude: 34.8333,
    longitude: 128.0833,
  ),
  // 43. 삼악산
  Mountain(
    id: 'mt_43',
    name: '삼악산',
    location: '강원 춘천',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 654,
    emoji: '🌲',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '의암호를 굽어보는 기암절벽과 등선폭포가 유명하며, 춘천의 대표 산행지입니다.',
    latitude: 37.8500,
    longitude: 127.7167,
  ),
  // 44. 선운산
  Mountain(
    id: 'mt_44',
    name: '선운산',
    location: '전북 고창',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 4.0,
    height: 336,
    emoji: '🗻',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '선운사 동백꽃 군락(천연기념물)이 유명하며, 도솔암의 마애불과 낙조가 아름답습니다.',
    latitude: 35.5000,
    longitude: 126.5833,
  ),
  // 45. 설악산
  Mountain(
    id: 'mt_45',
    name: '설악산',
    location: '강원 속초/인제/양양',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 12.0,
    height: 1708,
    emoji: '🌲',
    colors: [const Color(0xFF264653), const Color(0xFF2A9D8F)],
    description: '대한민국 대표 명산으로 유네스코 생물권보전지역이며, 울산바위·공룡능선 등 웅장한 경관을 자랑합니다.',
    latitude: 38.1194,
    longitude: 128.4656,
  ),
  // 46. 소백산
  Mountain(
    id: 'mt_46',
    name: '소백산',
    location: '충북 단양/경북 영주',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 11.0,
    height: 1440,
    emoji: '⛰️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '비로봉 일대의 철쭉 군락과 겨울 설화가 유명하며, 천문대와 함께 별 관측 명소입니다.',
    latitude: 36.9500,
    longitude: 128.4833,
  ),
  // 47. 소요산
  Mountain(
    id: 'mt_47',
    name: '소요산',
    location: '경기 동두천',
    difficulty: Difficulty.beginner,
    time: '약 3시간',
    distanceKm: 5.0,
    height: 587,
    emoji: '🏞️',
    colors: [const Color(0xFFE76F51), const Color(0xFF9B2226)],
    description: '경기 북부 최고의 단풍 명소로, 자재암과 폭포가 어우러진 계곡미가 빼어납니다.',
    latitude: 37.9333,
    longitude: 127.0667,
  ),
  // 48. 속리산
  Mountain(
    id: 'mt_48',
    name: '속리산',
    location: '충북 보은',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1058,
    emoji: '🗻',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '법주사의 금동미륵대불과 천왕봉 정상의 조망이 유명한 국립공원입니다.',
    latitude: 36.5333,
    longitude: 127.8667,
  ),
  // 49. 수락산
  Mountain(
    id: 'mt_49',
    name: '수락산',
    location: '서울 노원',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 5.5,
    height: 638,
    emoji: '🏔️',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '서울 동북쪽의 명산으로, 기암괴석과 계곡이 어우러져 사계절 시민들의 사랑을 받습니다.',
    latitude: 37.6720,
    longitude: 127.0726,
  ),
  // 50. 신불산
  Mountain(
    id: 'mt_50',
    name: '신불산',
    location: '울산',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1159,
    emoji: '⛰️',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '영남알프스의 핵심 산으로, 정상부의 광활한 억새평원이 가을이면 장관을 이룹니다.',
    latitude: 35.5000,
    longitude: 129.0500,
  ),
  // 51. 연인산
  Mountain(
    id: 'mt_51',
    name: '연인산',
    location: '경기 가평',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 1068,
    emoji: '🌲',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '연인끼리 함께 오르면 사랑이 이루어진다는 전설이 있으며, 철쭉 군락이 봄에 아름답습니다.',
    latitude: 37.8500,
    longitude: 127.3167,
  ),
  // 52. 오대산
  Mountain(
    id: 'mt_52',
    name: '오대산',
    location: '강원 홍천/평창',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 11.0,
    height: 1563,
    emoji: '🗻',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '월정사 전나무 숲길이 유명하며, 비로봉에서 보는 일출과 운해가 장관입니다.',
    latitude: 37.7833,
    longitude: 128.5500,
  ),
  // 53. 오봉산
  Mountain(
    id: 'mt_53',
    name: '오봉산',
    location: '강원 춘천',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 779,
    emoji: '🌲',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '다섯 개의 바위봉우리가 솟아 있어 오봉산이라 불리며, 소양호 조망이 뛰어납니다.',
    latitude: 37.9667,
    longitude: 127.7833,
  ),
  // 54. 용문산
  Mountain(
    id: 'mt_54',
    name: '용문산',
    location: '경기 양평',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1157,
    emoji: '⛰️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '천년 은행나무(천연기념물)가 있는 용문사를 품고 있으며, 경기도에서 두 번째로 높은 산입니다.',
    latitude: 37.5333,
    longitude: 127.5667,
  ),
  // 55. 용화산
  Mountain(
    id: 'mt_55',
    name: '용화산',
    location: '강원 춘천/화천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 878,
    emoji: '🏞️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '용이 승천한 전설이 깃든 산으로, 기암괴석과 북한강 조망이 아름답습니다.',
    latitude: 38.0000,
    longitude: 127.6833,
  ),
  // 56. 운문산
  Mountain(
    id: 'mt_56',
    name: '운문산',
    location: '경북 청도',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1188,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '운문사와 함께 천연기념물 처진소나무가 유명하며, 억새와 철쭉 군락이 아름답습니다.',
    latitude: 35.6833,
    longitude: 128.9667,
  ),
  // 57. 운악산
  Mountain(
    id: 'mt_57',
    name: '운악산',
    location: '경기 포천/가평',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 936,
    emoji: '🏔️',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '경기 소금강이라 불리며, 기암절벽과 수려한 계곡미로 유명합니다.',
    latitude: 37.8667,
    longitude: 127.2500,
  ),
  // 58. 운장산
  Mountain(
    id: 'mt_58',
    name: '운장산',
    location: '전북 진안',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1126,
    emoji: '⛰️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '전북의 지붕으로 불리며, 운일암반일암 계곡과 천상데크길이 인기 있습니다.',
    latitude: 35.8667,
    longitude: 127.4167,
  ),
  // 59. 월악산
  Mountain(
    id: 'mt_59',
    name: '월악산',
    location: '충북 제천/충주',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 1097,
    emoji: '🌲',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '충주호반과 어우러진 절경이 뛰어나며, 영봉 정상의 조망이 압도적입니다.',
    latitude: 36.8833,
    longitude: 128.1000,
  ),
  // 60. 월출산
  Mountain(
    id: 'mt_60',
    name: '월출산',
    location: '전남 영암',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 809,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '기암괴석이 장관인 남도의 금강산으로, 구름다리와 천황봉의 조망이 유명합니다.',
    latitude: 34.7667,
    longitude: 126.7000,
  ),
  // 61. 유명산
  Mountain(
    id: 'mt_61',
    name: '유명산',
    location: '경기 양평/가평',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 862,
    emoji: '🌲',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '가을 단풍과 억새가 아름다우며, 유명산자연휴양림과 연계한 산행이 인기입니다.',
    latitude: 37.5667,
    longitude: 127.5000,
  ),
  // 62. 응봉산
  Mountain(
    id: 'mt_62',
    name: '응봉산',
    location: '강원 삼척',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 999,
    emoji: '⛰️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '용소골 계곡의 비경이 유명하며, 덕풍계곡과 연계한 산행 코스가 알려져 있습니다.',
    latitude: 37.2333,
    longitude: 129.1500,
  ),
  // 63. 장안산
  Mountain(
    id: 'mt_63',
    name: '장안산',
    location: '전북 장수',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.5,
    height: 1237,
    emoji: '🏞️',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '덕산용소에서 시작하는 계곡 산행이 유명하며, 가을 단풍이 특히 아름답습니다.',
    latitude: 35.6500,
    longitude: 127.5833,
  ),
  // 64. 재약산
  Mountain(
    id: 'mt_64',
    name: '재약산',
    location: '경남 밀양',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1189,
    emoji: '🗻',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '영남알프스의 중심 산으로, 표충사와 사자평 억새밭이 가을 명소로 유명합니다.',
    latitude: 35.5333,
    longitude: 129.0167,
  ),
  // 65. 적상산
  Mountain(
    id: 'mt_65',
    name: '적상산',
    location: '전북 무주',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1034,
    emoji: '🏔️',
    colors: [const Color(0xFFE76F51), const Color(0xFF9B2226)],
    description: '가을이면 산 전체가 붉게 물들어 적상(赤裳)이라 불리며, 안국사와 머루와인동굴이 있습니다.',
    latitude: 35.9167,
    longitude: 127.7000,
  ),
  // 66. 점봉산
  Mountain(
    id: 'mt_66',
    name: '점봉산',
    location: '강원 인제/양양',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1424,
    emoji: '⛰️',
    colors: [const Color(0xFF264653), const Color(0xFF2A9D8F)],
    description: '설악산 남쪽의 비경으로, 곰배령 야생화 군락지가 천상의 화원으로 불립니다.',
    latitude: 38.0333,
    longitude: 128.4333,
  ),
  // 67. 조계산
  Mountain(
    id: 'mt_67',
    name: '조계산',
    location: '전남 순천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 884,
    emoji: '🌲',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '송광사와 선암사 두 천년고찰을 품은 산으로, 두 사찰을 잇는 종주코스가 인기입니다.',
    latitude: 35.0167,
    longitude: 127.0167,
  ),
  // 68. 주왕산
  Mountain(
    id: 'mt_68',
    name: '주왕산',
    location: '경북 청송',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.5,
    height: 721,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '한국의 3대 암산으로, 주왕굴과 절골계곡, 주산지의 수몰 왕버들이 유명합니다.',
    latitude: 36.3833,
    longitude: 129.1667,
  ),
  // 69. 주흘산
  Mountain(
    id: 'mt_69',
    name: '주흘산',
    location: '경북 문경',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1106,
    emoji: '🌲',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '문경새재(조령)를 품고 있으며, 영남대로의 관문 역할을 했던 역사적 산입니다.',
    latitude: 36.7167,
    longitude: 128.0500,
  ),
  // 70. 지리산
  Mountain(
    id: 'mt_70',
    name: '지리산',
    location: '전남/경남/전북',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 12.0,
    height: 1915,
    emoji: '⛰️',
    colors: [const Color(0xFF264653), const Color(0xFF2A9D8F)],
    description: '한국 최초의 국립공원이자 남한 내륙 최고봉 천왕봉을 가진 민족의 영산입니다.',
    latitude: 35.3372,
    longitude: 127.7306,
  ),
  // 71. 천관산
  Mountain(
    id: 'mt_71',
    name: '천관산',
    location: '전남 장흥',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 723,
    emoji: '🏞️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '호남 5대 명산 중 하나로, 억새와 동백꽃이 계절마다 산을 물들이며 다도해 조망이 뛰어납니다.',
    latitude: 34.6167,
    longitude: 126.9500,
  ),
  // 72. 천마산
  Mountain(
    id: 'mt_72',
    name: '천마산',
    location: '경기 남양주',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 812,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '수도권에서 접근이 편리한 산으로, 다양한 등산로와 봄 진달래가 유명합니다.',
    latitude: 37.6167,
    longitude: 127.1667,
  ),
  // 73. 천성산
  Mountain(
    id: 'mt_73',
    name: '천성산',
    location: '경남 양산',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 922,
    emoji: '🏔️',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '내원사와 화엄늪 습지가 유명하며, 정상부의 억새평원에서 낙동강 하구를 조망할 수 있습니다.',
    latitude: 35.4333,
    longitude: 129.0833,
  ),
  // 74. 천태산
  Mountain(
    id: 'mt_74',
    name: '천태산',
    location: '충북 영동',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 715,
    emoji: '⛰️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '영국사의 은행나무(천연기념물)와 망탑봉 석탑이 유명하며, 반야사 계곡이 아름답습니다.',
    latitude: 36.1000,
    longitude: 127.8167,
  ),
  // 75. 청계산
  Mountain(
    id: 'mt_75',
    name: '청계산',
    location: '서울/경기',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.5,
    height: 618,
    emoji: '🌲',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '서울 근교에서 가장 인기 있는 등산 코스로, 매봉 정상에서 서울 전경이 펼쳐집니다.',
    latitude: 37.4437,
    longitude: 127.0557,
  ),
  // 76. 청량산
  Mountain(
    id: 'mt_76',
    name: '청량산',
    location: '경북 봉화',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 870,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '퇴계 이황이 사랑한 산으로, 12봉과 암봉 사이의 하늘다리가 스릴 만점입니다.',
    latitude: 36.8333,
    longitude: 128.9333,
  ),
  // 77. 추월산
  Mountain(
    id: 'mt_77',
    name: '추월산',
    location: '전남 담양',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 731,
    emoji: '🌲',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '가을 달밤의 정취가 아름다워 이름 붙여졌으며, 담양호와 메타세쿼이아 가로수길이 가깝습니다.',
    latitude: 35.2667,
    longitude: 127.0167,
  ),
  // 78. 축령산
  Mountain(
    id: 'mt_78',
    name: '축령산',
    location: '전남 장성',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 5.5,
    height: 621,
    emoji: '⛰️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '편백나무 숲이 울창하여 산림욕의 성지로 불리며, 피톤치드 가득한 치유의 숲입니다.',
    latitude: 35.3667,
    longitude: 126.8833,
  ),
  // 79. 치악산
  Mountain(
    id: 'mt_79',
    name: '치악산',
    location: '강원 원주',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1288,
    emoji: '🏞️',
    colors: [const Color(0xFF264653), const Color(0xFF2A9D8F)],
    description: '은혜 갚은 꿩 전설로 유명하며, 비로봉까지의 종주 코스는 상당한 체력을 요합니다.',
    latitude: 37.3667,
    longitude: 128.0500,
  ),
  // 80. 칠갑산
  Mountain(
    id: 'mt_80',
    name: '칠갑산',
    location: '충남 청양',
    difficulty: Difficulty.beginner,
    time: '약 3시간',
    distanceKm: 5.0,
    height: 561,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '대중가요 "칠갑산"으로 유명해진 산으로, 장곡사와 천장호 출렁다리가 명소입니다.',
    latitude: 36.4000,
    longitude: 126.8667,
  ),
  // 81. 태백산
  Mountain(
    id: 'mt_81',
    name: '태백산',
    location: '강원 태백/영월',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.5,
    height: 1567,
    emoji: '🏔️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '천제단에서 지내는 개천대제로 유명하며, 겨울 눈꽃축제와 주목 군락이 장관입니다.',
    latitude: 37.0833,
    longitude: 128.9167,
  ),
  // 82. 태화산
  Mountain(
    id: 'mt_82',
    name: '태화산',
    location: '강원 영월',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1027,
    emoji: '⛰️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '고씨동굴 위에 자리한 산으로, 석회암 지대 특유의 독특한 식생과 지형이 특징입니다.',
    latitude: 37.2167,
    longitude: 128.5833,
  ),
  // 83. 팔공산
  Mountain(
    id: 'mt_83',
    name: '팔공산',
    location: '대구/경북 칠곡',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1193,
    emoji: '🌲',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '갓바위(관봉석조여래좌상)로 유명하며, 동화사와 은해사 등 유서 깊은 사찰이 있습니다.',
    latitude: 35.9833,
    longitude: 128.6833,
  ),
  // 84. 팔봉산
  Mountain(
    id: 'mt_84',
    name: '팔봉산',
    location: '강원 홍천',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 3.0,
    height: 328,
    emoji: '🗻',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '여덟 개의 봉우리가 홍천강을 따라 펼쳐지며, 짧지만 암릉 구간이 스릴 넘칩니다.',
    latitude: 37.7500,
    longitude: 127.8833,
  ),
  // 85. 팔영산
  Mountain(
    id: 'mt_85',
    name: '팔영산',
    location: '전남 고흥',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.0,
    height: 609,
    emoji: '🌲',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '여덟 개의 바위봉우리가 능가사를 병풍처럼 두르고 있으며, 다도해 조망이 탁월합니다.',
    latitude: 34.6000,
    longitude: 127.3167,
  ),
  // 86. 한라산
  Mountain(
    id: 'mt_86',
    name: '한라산',
    location: '제주',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 12.0,
    height: 1950,
    emoji: '⛰️',
    colors: [const Color(0xFF264653), const Color(0xFF2A9D8F)],
    description: '남한 최고봉으로 유네스코 세계자연유산이며, 백록담 분화구와 사계절 풍경이 압권입니다.',
    latitude: 33.3617,
    longitude: 126.5292,
  ),
  // 87. 함백산
  Mountain(
    id: 'mt_87',
    name: '함백산',
    location: '강원 태백/정선',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.0,
    height: 1573,
    emoji: '🏞️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '남한에서 다섯 번째로 높은 산으로, 만항재에서 출발하면 비교적 수월하게 정상에 오를 수 있습니다.',
    latitude: 37.1333,
    longitude: 128.9167,
  ),
  // 88. 화악산
  Mountain(
    id: 'mt_88',
    name: '화악산',
    location: '경기 가평/강원 춘천',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 10.0,
    height: 1468,
    emoji: '🗻',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '경기도 최고봉 명지산보다 높은 봉우리로, 군사지역이라 입산이 제한적이지만 비경을 간직하고 있습니다.',
    latitude: 37.9500,
    longitude: 127.5167,
  ),
  // 89. 화왕산
  Mountain(
    id: 'mt_89',
    name: '화왕산',
    location: '경남 창녕',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.5,
    height: 757,
    emoji: '🏔️',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '정월대보름 억새 태우기 행사로 유명하며, 정상부 억새평원과 창녕 우포늪 조망이 장관입니다.',
    latitude: 35.5667,
    longitude: 128.5500,
  ),
  // 90. 황매산
  Mountain(
    id: 'mt_90',
    name: '황매산',
    location: '경남 합천/산청',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 1108,
    emoji: '⛰️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '봄 철쭉 군락이 한국 최대 규모로, 한국의 매화꽃 산이라 불리는 절경의 산입니다.',
    latitude: 35.5833,
    longitude: 127.9833,
  ),
  // 91. 황석산
  Mountain(
    id: 'mt_91',
    name: '황석산',
    location: '경남 함양',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 8.0,
    height: 1190,
    emoji: '🌲',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '임진왜란 의병 항전지인 황석산성이 있으며, 가을 단풍과 기암절벽이 어우러진 명산입니다.',
    latitude: 35.5167,
    longitude: 127.6833,
  ),
  // 92. 황악산
  Mountain(
    id: 'mt_92',
    name: '황악산',
    location: '경북 김천',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.5,
    height: 1111,
    emoji: '🗻',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '직지사를 품은 산으로, 능여계곡의 시원한 물줄기와 사계절 숲길이 아름답습니다.',
    latitude: 36.1333,
    longitude: 128.0167,
  ),
  // 93. 희양산
  Mountain(
    id: 'mt_93',
    name: '희양산',
    location: '경북 문경/충북 괴산',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 999,
    emoji: '🌲',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '봉암사(출입제한)를 품고 있으며, 가파른 암릉과 깊은 골짜기가 비경을 이룹니다.',
    latitude: 36.7833,
    longitude: 128.0167,
  ),
  // 94. 가지산
  Mountain(
    id: 'mt_94',
    name: '가지산',
    location: '울산/경남',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.5,
    height: 1241,
    emoji: '⛰️',
    colors: [const Color(0xFFA68A64), const Color(0xFF656D4A)],
    description: '영남알프스 최고봉으로, 석남사에서 출발하는 코스와 쌀바위 조망이 유명합니다.',
    latitude: 35.5833,
    longitude: 129.0667,
  ),
  // 95. 대둔산
  Mountain(
    id: 'mt_95',
    name: '대둔산',
    location: '충남 논산/전북 완주',
    difficulty: Difficulty.intermediate,
    time: '약 4-5시간',
    distanceKm: 7.0,
    height: 878,
    emoji: '🏞️',
    colors: [const Color(0xFF52B788), const Color(0xFF2D6A4F)],
    description: '기암괴석과 금강구름다리, 태고사 마애불이 유명하며 호남의 금강산으로 불립니다.',
    latitude: 36.1167,
    longitude: 127.2167,
  ),
  // 96. 대암산
  Mountain(
    id: 'mt_96',
    name: '대암산',
    location: '강원 인제',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.0,
    height: 1304,
    emoji: '🗻',
    colors: [const Color(0xFF74B3CE), const Color(0xFF1B4332)],
    description: '용늪(람사르습지)을 품고 있는 산으로, 고층습원의 생태적 가치가 뛰어납니다.',
    latitude: 38.1667,
    longitude: 128.1333,
  ),
  // 97. 도봉산
  Mountain(
    id: 'mt_97',
    name: '도봉산',
    location: '서울/경기 양주',
    difficulty: Difficulty.intermediate,
    time: '약 3시간',
    distanceKm: 6.5,
    height: 740,
    emoji: '🏔️',
    colors: [const Color(0xFFFF8C42), const Color(0xFFB5451B)],
    description: '북한산 국립공원에 속하며, 자운봉·만장봉·선인봉의 화강암 봉우리가 웅장합니다.',
    latitude: 37.6972,
    longitude: 127.0147,
  ),
  // 98. 불암산
  Mountain(
    id: 'mt_98',
    name: '불암산',
    location: '서울/경기 남양주',
    difficulty: Difficulty.beginner,
    time: '약 3시간',
    distanceKm: 5.0,
    height: 508,
    emoji: '⛰️',
    colors: [const Color(0xFF95D5B2), const Color(0xFF40916C)],
    description: '부처 형상의 바위가 있어 이름 붙여졌으며, 서울 동북부 시민들의 대표 근교 산입니다.',
    latitude: 37.6544,
    longitude: 127.0695,
  ),
  // 99. 아차산
  Mountain(
    id: 'mt_99',
    name: '아차산',
    location: '서울',
    difficulty: Difficulty.beginner,
    time: '약 2시간',
    distanceKm: 3.5,
    height: 285,
    emoji: '🌲',
    colors: [const Color(0xFF8ECAE6), const Color(0xFF219EBC)],
    description: '고구려 온달장군의 전설이 깃든 산으로, 한강과 서울 도심 조망이 탁월한 도심 속 명산입니다.',
    latitude: 37.5704,
    longitude: 127.1044,
  ),
  // 100. 덕산 (보너스 - 100번째)
  Mountain(
    id: 'mt_100',
    name: '가리봉',
    location: '강원 인제/양양',
    difficulty: Difficulty.advanced,
    time: '약 6-8시간',
    distanceKm: 9.0,
    height: 1519,
    emoji: '🗻',
    colors: [const Color(0xFF6A994E), const Color(0xFF386641)],
    description: '설악산 남쪽 자락의 봉우리로, 원시림과 야생화가 잘 보존된 강원도의 숨은 명산입니다.',
    latitude: 38.0500,
    longitude: 128.3667,
  ),
];
